AllCops:
  Exclude:
    - 'test/**/*'
    - 'tmp/**/*'
    - 'bin/**/*'
    - 'Rakefile'
    - '*.gemspec'
Metrics/AbcSize:
  Max: 16 # TODO Lower to default 15

Metrics/MethodLength:
  CountComments: false
  Max: 15 # TODO Lower to default 10
